### ISSUE TITLE
[0.7] tells me Unsupported driver [ws]

### ISSUE THREAD

**Issue by moneya** [Laragear/Surreal#2]
### PHP & Platform

8.2  - laravel valet

### Database

surreal

### Laravel version

9.19

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

when i run artisan migrate, i expect the migration file to run for a structure database.

### Description

Unsupported driver [ws]  and also Unsupported driver [surreal]

### Reproduction

```php
php artisan migrate
```

### Stack trace & logs

```shell
[2023-01-06 15:03:31] local.ERROR: Unsupported driver [surreal]. {"exception":"[object] (InvalidArgumentException(code: 0): Unsupported driver [surreal]. at /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:274)
[stacktrace]
#0 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(75): Illuminate\\Database\\Connectors\\ConnectionFactory->createConnection('surreal', Object(Closure), 'rpc', '', Array)
#1 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(50): Illuminate\\Database\\Connectors\\ConnectionFactory->createSingleConnection(Array)
#2 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(145): Illuminate\\Database\\Connectors\\ConnectionFactory->make(Array, 'surreal')
#3 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(100): Illuminate\\Database\\DatabaseManager->makeConnection('surreal')
#4 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(211): Illuminate\\Database\\DatabaseManager->connection('surreal')
#5 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(167): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->getConnection()
#6 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(682): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#7 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(138): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#8 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Support/helpers.php(247): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}(1)
#9 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(138): retry(1, Object(Closure), 0, Object(Closure))
#10 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(114): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#11 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(82): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#12 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(615): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#13 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection(NULL, Object(Closure))
#14 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#15 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#17 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#18 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#19 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call(Array)
#20 /Users/whitefang/projects/web/laravel/surreal/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Console/Command.php(151): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 /Users/whitefang/projects/web/laravel/surreal/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /Users/whitefang/projects/web/laravel/surreal/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /Users/whitefang/projects/web/laravel/surreal/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /Users/whitefang/projects/web/laravel/surreal/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /Users/whitefang/projects/web/laravel/surreal/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 {main}
"}
```

**Comment by DarkGhostHunter** [comment]
PR are welcome while I'm hands full.

**Comment by katyusha777** [comment]
Adding the service provider to my config/app.php solved this for me.
```php
SurrealServiceProvider::class,
```

**Comment by RVxLab** [comment]
I created a PR that addresses this by adding auto discovery.
